language: python

install:
  - "pip install -r requirements.txt"
  - pip install coveralls

script:
  - coverage run --source=ghx\ghx test/test_ghx.py
  - python test/test_ghx.py

after_success:
  coveralls